### PR TITLE
Fixes blocking container class issue

### PR DESCRIPTION
**Pull request by scott-joe-williams**

### CODE REVIEW

**Comment by scott-joe-williams** [comment]
Fixes https://github.com/ExactTarget/fuelux-mctheme/issues/294

**Comment by interactivellama** [comment]
Why is one `btn-group-xl > .btn-lg` and the other `btn-group-sm .btn-sm`?

**Comment by interactivellama** [comment]
Please remove `dist` files from commits, please.

**Comment by scott-joe-williams** [comment]
The `dist` files are in the repo now, but okay. And I'll fix the `>` mistake.

**Comment by scott-joe-williams** [comment]
Ugh. the typos are me trying to do too many things at the same time.

I still don't understand the request to move `dist` files from a commit, but leaving `dist` files in the repo. If it's a matter of keeping the directory, but not the files, you can just do this http://stackoverflow.com/questions/5600621/gitignore-exclude-files-in-directory-but-not-certain-directories

**Pull request closed without merging**
