### PR TITLE
Add three content icons

### LINKED ISSUE #440: Add additional icons to content icons
Add a blue padlock, a blue three person icon and a two person plus icon. Requested by @byersjul

### PR DESCRIPTION
**Pull request by interactivellama**
Add a blue padlock, a blue three person icon and a two person plus icon. Requested by @byersjul 

screen shot 2015-12-21 at 12 05 23 pm

Fixes #440

### CODE REVIEW

**Comment by swilliamset** [comment]
@jamin-hall need some feedback here

should we be continuing to create gradated icons? when creating icons should we consider various possible states (locked and unlocked for instances) even if they aren't explicitly requested?

**Comment by jamin-hall** [comment]
@swilliamset and @interactivellama I'll follow up with @byersjul. We may have reviewed this, but it's not coming to mind. 

In general, we should consider the common states when creating an icon. Normal, hover, active, disabled, and combinations of those states. 

As for gradients, let's plan on flattening icons from now on. With Lightning on the horizon, flattening the icons will be one more way we can prepare for change. Spoke to Jane at DesignMap and she's in agreement.

**Comment by interactivellama** [comment]
@jamin-hall For context, these are used on a menu sidebar of modal at a large size (50px+) on a gray background.

Please communicate this with designers also. We are trying to get away from UXA modifying icons for designers.

**Comment by swilliamset** [comment]
Also why are we using blue icon on gray background here versus white icon
as seen elsewhere?

**Comment by jamin-hall** [comment]
Not sure about white on gray. Reaching an accessible contrast could get tricky. What is the elsewhere you're referring to @swilliamset ?

Thanks @interactivellama that sparks a memory. We've framed these as icons, but I wonder if they're actually images. That seems like semantics.Just wondering if these are more content images, and if so maybe we don't need to add them to the icon set. Probably a much larger discussion to be had here about the difference between an icon and an image.

Either way we should definitely make sure things are consistent thematically. I will talk to Julie about flattening the style so that @interactivellama doesn't need to rework the asset.

**Comment by swilliamset** [comment]
image

**Comment by swilliamset** [comment]
@jamin-hall i would say icon versus whatever is a semantics debate. what else do we need to move forward on this?

**Comment by swilliamset** [comment]
@interactivellama the branch needs to be updated

**Comment by interactivellama** [comment]
Updated and prevented conflicts with last two icon PRs.

**Pull request merged**
