### PR TITLE
Restricted icon for slots (content editor)

### PR DESCRIPTION
**Pull request by interactivellama**
Adds 

screen shot 2015-11-23 at 4 27 03 pm

### CODE REVIEW

**Comment by interactivellama** [comment]
Waiting for approval from design.

**Comment by swilliamset** [comment]
Flatten red icon based on https://github.com/ExactTarget/fuelux-mctheme/pull/441#issuecomment-166405414

**Comment by swilliamset** [comment]
@interactivellama need an update here

**Comment by jamin-hall** [comment]
Spoke with Stephanie. I was confused by the attached examples because of
the gray rectangular background on the third image. Did we add that
background to help with the example (because the icon is white) or is it
part of the icon? If we can verify that the rectangle is NOT part of the
icon these look good. Thanks.

On Tue, Jan 19, 2016 at 1:17 PM, Stephen W. Williams <
notifications@github.com> wrote:

> @interactivellama <https://github.com/interactivellama> need an update
> here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExactTarget/fuelux-mctheme/pull/427#issuecomment-172939074>
> .
>



-- 

JAMIN HALL

Lead Interaction Designer | salesforce.com

Mobile: 317-701-4990

**Comment by interactivellama** [comment]
Not part of icon design.

Yes, all icons with `-white` at the end of their name get a gray background on the site.
http://fuelux-mctheme.herokuapp.com/examples/icons/icons-content.html

@swilliamset 's original issue was the gradient on the red icon I think.

**Comment by interactivellama** [comment]
I flattened the icon and am merging. I also synced the AI file, because this PR has been sitting here so long.....other icons have been modified. :frowning:

**Comment by interactivellama** [comment]
Now updating #441 with additional icons changes. I suggest we move away from keeping all icons in "binary" AI files. I know it's good for consistency. It's a git nightmare though.

**Pull request merged**
