### PR TITLE
reduced width of secondary paging input on repeater to accomodate 3 digits by default

### LINKED ISSUE #138: Smaller width needs to be set for .secondaryPaging
A smaller width should be set for `.repeater .repeater-secondaryPaging` to only show three digits. Probably around `40px`.

### PR DESCRIPTION
**Pull request by mbeard**
Fixes #138

### CODE REVIEW

**Comment by interactivellama** [comment]
37px looks best to me.

**Comment by interactivellama** [comment]
@jamin-hall Also should this be left or right aligned?
screenshot 2015-02-03 13 37 37

**Comment by mbeard** [comment]
I can make it 37px.  Realized I modified the wrong file here anyway.  Here's what it looks like right aligned for reference.

screenshot 2015-02-03 13 57 04

**Comment by jamin-hall** [comment]
Let's go with left alignment for now to account for the dropdown indicator that sometimes appears in the field. Thanks.

JAMIN HALL
Lead Interaction Designer | salesforce.com
Mobile: 317-701-4990

**Comment by interactivellama** [comment]
That's a different control within the repeater. A smaller input will not mess up the drop down. Unless you are wanting both to be the same size even without the drop down.

**Pull request merged**
