### PR TITLE
Add content editor icons

### LINKED ISSUE #376: Add content editor icons
Add the following icons for content editor for the current sprint:
https://drive.google.com/drive/folders/0B-D_syotakCufldjcUhEUFRENVpHallVejNhOS1YWGgtWDd1TlhZN1ZuTjVlRkRmNUhBNEU

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #376.

List of all updated icons:

fireshot capture 10 - fuel ux 3 icons - http___localhost_8000_examples_icons_icons html

### CODE REVIEW

**Comment by interactivellama** [comment]
Looks like magin bottom is missing.

**Comment by interactivellama** [comment]
@cormacmccarthy Missing icons are fixed.

Fuel UX via bower is present in this merge due to https://github.com/ExactTarget/fuelux-mctheme/pull/368 I don't have any information about that PR though.

**Comment by swilliamset** [comment]
Lock icons are a bit janky. One is smaller than the other and they are offset to the left.
screen shot 2015-09-04 at 1 12 53 pm

Dots are missed align
screen shot 2015-09-04 at 1 16 44 pm

screen shot 2015-09-04 at 1 17 38 pm

**Comment by interactivellama** [comment]
@swilliamset Updated with latest screen capture

**Pull request merged**
