### PR TITLE
Round 2 of iconography for Marketing Cloud Theme.

### LINKED ISSUE #193: Complete step 2 of iconography for MCtheme
## Fill out SVG icons from the "sprite"

There was a sprite sheet in the project:

https://github.com/ExactTarget/fuelux-mctheme/blob/1.3.0/img/spritesheet-2x.png

...that is not currently fully represented by SVG icons.

Also in the [Source Art](https://github.exacttarget.com/CNX14/source-art) project are various icon and sprite files that should be considered for making SVG icons of, including:

fuelux-icon-medium-spritetemplate

...and...

action-icons

...not to mention the huge list of things brought up here:

https://github.exacttarget.com/CNX14/source-art/tree/master/research

...and here:

https://docs.google.com/a/salesforce.com/spreadsheets/d/1krrR_Lt7OE5hZrsBwXkIDHM1FcPe3ZliVHrMaVtpQhU/edit#gid=56206714

For now I (@chriscorwin) will go through and sort out what we have vs what we should do for "step 2".

At this point, I suspect my recommendation will be to *only* do the sprite that was in MC Theme and also make a "step 3" issue that rounds up and creates icons for the various apps as mentioned in the Google Doc above.

### PR DESCRIPTION
**Pull request by chriscorwin**
Fixes #193

### CODE REVIEW

**Comment by interactivellama** [comment]
Do any of these need UXDS design approval or am I able to approve them?

**Comment by mbeard** [comment]
Do you have a PNG/PDF of these that we can take a peek at?

**Comment by interactivellama** [comment]
fuel ux 3 icons

**Comment by jamin-hall** [comment]
My eyes are dilated right now, so I'd like to take a more thorough look tomorrow. A couple of immediate thoughts:


 *   For some reason the yellow in the .fuelux-icon-pencil-hover seems to clash with the rest of the color scheme. Did we copy this from the original icon?
 *   Are we set on the names for each icon? I wonder if we could shorten some of them. Also, wondering if some could be renamed to reflect intended usage a little more.

Really like how the set is coming together. This is so much better than having multiple icon sets floating around.

**Comment by rachprice** [comment]
@jamin-hall The pencil does look like it was pulled from the original.

**Comment by chriscorwin** [comment]
>  For some reason the yellow in the .fuelux-icon-pencil-hover seems to clash with the rest of the color scheme. Did we copy this from the original icon?

Yes, at 13px it looks nearly identical do the old, shitty, jpeg version.

What I'd like to eventually do is have media queries that show different versions of the icons for hi-res monitors or when being used in a bigger context and that clear up all those annoying inconsistencies like the blaring yellow pencil lead outta nowhere.

OOOOOOOR perhaps be a part of the icon planning / drawing for the 2.0 version of the theme... ?

**Comment by chriscorwin** [comment]
>  Are we set on the names for each icon? I wonder if we could shorten some of them. Also, wondering if some could be renamed to reflect intended usage a little more.

I've adopted names that were already in use.

For icons I hold to the school of thought that says the name of the icon should describe the _object_, not the _intended use_ of the object.

I call it `.spyglass` rather than `.search`, for instance, because that is what the artwork is.

We happen to use a "spyglass" to represent a searching action, but the "glyph" itself is not "search".

I've not been 100% consistent in the application of this theory, but, as I said above, I have _also_ followed existing naming conventions where they exist.

**Comment by chriscorwin** [comment]
Oh, @jamin-hall and @rachprice : see _____^

**Comment by chriscorwin** [comment]
Oh, and to be more explicit, @jamin-hall, no, we can't rename them, it would be a breaking change at this point.

It'll be okay though, as the base name is all that really matters, and even in the longest one `.fuelux-icon-checkbox-intermediate-disabled`, it can generally be referred to by humans as `checkbox-intermediate` and the programming will take care of the rest of it.

**Comment by jamin-hall** [comment]
Okay. Cool. We're fine for now then. Definitely think it would be good to include you in the 2.0 work @chriscorwin.

**Pull request merged**
