### PR TITLE
Gh222   svg icons less file being included multiple times

### PR DESCRIPTION
**Pull request by chriscorwin**
Fixes issue #222

### CODE REVIEW

**Comment by interactivellama** [comment]
I'm not seeing any icons on `http://localhost:8001/less/icons/preview.html` now.

**Comment by interactivellama** [comment]
When I made icons I got: 

screen shot 2015-04-06 at 3 31 24 pm

instead of 
screenshot 2015-04-06 15 29 29

**Comment by interactivellama** [comment]
`class="fuelux"` needs to be added to `preview.html` and the `examples/icons/preview.html`may need to be removed to avoid confusion

**Comment by chriscorwin** [comment]
The icons preview thing is now being built into the proper place, but I had to kinda hack up grunticon to do it.

That hack won't get checked in --- so the file that gets built is good... but if *anyone else* tries to make the icons, it won't look right unless they also add my hack:

Added this:

```		var step = 6,
			i = 0,
			L = prevData.icons.length;
		for (; i < L; i += step) {
			prevData.rows.push({rowicons:prevData.icons.slice(i, i + step)});
		}
		;
```

...to `node_modules/grunt-grunticon/lib/grunticon-helper.js`.


Fixed the calendar icons. The issue was that the `grunt svgmin` task was getting pretty greedy with its optimizations. I expanded the appearance and combined the offending paths in illustrator and re-exported those icons, so now the optimization looks just like it is supposed. to.

**Pull request closed without merging**
