### PR TITLE
Color palette reduction and variable creation (Part 2)

### PR DESCRIPTION
**Pull request by interactivellama**
@jamin-hall I wanted to PR this before it got any more out of date. It's been on hold since February.

I'm not emotionally attached to any of the color names and some of them are actually inconsistent. Blue as prefix, blue as suffix kind of thing. I just wanted to set this out there to discuss in order to move forward.

Here's the [associated deployment for preview](http://mctheme-styleguide-sync.herokuapp.com/).

Swatches are available here now: http://mctheme-styleguide-sync.herokuapp.com/examples/colors/colors.html
_This will eventually need to be squashed._

Sample of swatch page. This should help @Alondite00 with his tasks, too.
**[OLD, PLEASE LOOK AT NEW SWATCH LIST]**
fireshot capture - marketing cloud colors - http___localhost_8000_examples_colors_colors html

[#1379](https://github.com/ExactTarget/fuelux/pull/1379) in Fuel UX proper should help prevent many colors "bleeding through".

### CODE REVIEW

**Comment by interactivellama** [comment]
Updated with current example markup, so that only the LESS files are changed.

**Comment by interactivellama** [comment]
@jamin-hall All the colors have been moved into `variables.less`. All variables should be in that one file in order to make them findable. The latest pages can be viewed at http://mctheme-styleguide-sync.herokuapp.com/ Please review/red-line. I am sure there are some slight color changes we may not want.

**Comment by swilliamset** [comment]
hold waiting for feedback from @jamin-hall jamin

**Comment by swilliamset** [comment]
@interactivellama this needs a rebase

**Comment by interactivellama** [comment]
Yes. @jamin-hall and Rachel have a bunch of red lines (and changes to their prescribed design) that they are going to review of the next week or two.

**Comment by interactivellama** [comment]
Apologies to anyone who's seen `red-indian` as a color name. It was originally "Indian Red" like the Crayola crayon which is based off a pigment from the country of India, not any pejorative term.

**Comment by interactivellama** [comment]
Updated with SLDS success colors. (At Rachel's suggestion)

screenshot 2015-08-24 12 24 34
screenshot 2015-08-24 12 26 03

I will implement the dark green one.

**Comment by interactivellama** [comment]
Old MCtheme green (before this PR)
screenshot 2015-08-24 13 21 39

Aligned w/ SLDS:
screenshot 2015-08-24 13 21 41

**Comment by interactivellama** [comment]
Modal and wizard borders with gray87 instead of gray80 and gray93 respectively. 

screenshot 2015-08-24 14 32 31
screenshot 2015-08-24 14 32 39

**Comment by interactivellama** [comment]
Changing danger-dark to #c23934

Allows AA compliance of contrast Ratio: 4.74:1

screenshot 2015-08-24 15 36 07

**Comment by interactivellama** [comment]
Changed popover border to gray80 instead of gray74. This will align with wizard and modal changes mentioned earlier.

screenshot 2015-08-24 16 30 36

**Comment by interactivellama** [comment]
Updated color palette:
fireshot capture - marketing cloud colors - http___localhost_8000_examples_colors_colors html

**Comment by interactivellama** [comment]
@jamin-hall I've implemented the red lines you asked for.

Latest version is here:
http://mctheme-styleguide-sync.herokuapp.com/examples/colors/colors.html

@Alondite00 @dwaltz Hopefully this will allow [these colors](http://mctheme-styleguide-sync.herokuapp.com/examples/colors/colors.html) to go in the style guide. Although the more semantically named design tokens from SLDS need to added in another PR what aliases these color names.

**Comment by mbeard** [comment]
With the changes, the font and border color of an active button (in focus) is now black.

screenshot 2015-08-25 13 22 46

**Comment by swilliamset** [comment]
@interactivellama Please resolve merge conflict

**Comment by mbeard** [comment]
The styling of the default tooltips seems off.
screenshot 2015-08-25 13 28 10

**Comment by interactivellama** [comment]
@swilliamset Conflict merged

**Comment by jamin-hall** [comment]
Does that mean the sync link is updated?

On Tue, Aug 25, 2015 at 1:40 PM, Stephen James <notifications@github.com>
wrote:

> @swilliamset <https://github.com/swilliamset> Conflict merged
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExactTarget/fuelux-mctheme/pull/299#issuecomment-134681235>
> .
>



-- 

JAMIN HALL

Lead Interaction Designer | salesforce.com

Mobile: 317-701-4990

**Comment by interactivellama** [comment]
@mbeard 

http://fuelux-mctheme.herokuapp.com/examples/bootstrap-javascript/bootstrap-javascript.html

One of these is the current and one is this PR. I'm not seeing a difference.
screen shot 2015-08-25 at 1 42 36 pm
screen shot 2015-08-25 at 1 45 13 pm

**Comment by interactivellama** [comment]
@jamin-hall Sync link is all updated manually by me.

**Comment by interactivellama** [comment]
@mbeard Button focus fixed to blue
screen shot 2015-08-25 at 2 34 20 pm


https://github.com/interactivellama/fuelux-mctheme/commit/c1d7b870a1aca907fe68672f8d661e0995841ac4

**Comment by jamin-hall** [comment]
Found another issue. When hovering over a selected toggle item the text and
border turn gray/black. This is unexpected.

[image: Inline image 1]

Looks like the issue is buttons.less:29

.btn-default:active:hover,.btn-default.active:hover, .open >
.dropdown-toggle.btn-default:hover, .btn-default:active:focus,
.btn-default.active:focus, .open > .dropdown-toggle.btn-default:focus,
.btn-default:active.focus, .btn-default.active.focus, .open >
.dropdown-toggle.btn-default.focus {

   1. color: #333;
      2. background-color: #d4d4d4;
      3. border-color: #8c8c8c;

}

On Tue, Aug 25, 2015 at 2:34 PM, Stephen James <notifications@github.com>
wrote:

> @mbeard <https://github.com/mbeard> Button focus fixed to blue
> [image: screen shot 2015-08-25 at 2 34 20 pm]
> <https://cloud.githubusercontent.com/assets/1290832/9475713/63c180ba-4b36-11e5-8920-b88a4514ced1.png>
>
> interactivellama@c1d7b87
> <https://github.com/interactivellama/fuelux-mctheme/commit/c1d7b870a1aca907fe68672f8d661e0995841ac4>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExactTarget/fuelux-mctheme/pull/299#issuecomment-134695593>
> .
>



-- 

JAMIN HALL

Lead Interaction Designer | salesforce.com

Mobile: 317-701-4990

**Comment by interactivellama** [comment]
@jamin-hall This is same issue Matt found. 

Fixed by:
https://github.com/interactivellama/fuelux-mctheme/commit/c1d7b870a1aca907fe68672f8d661e0995841ac4

**Comment by interactivellama** [comment]
Updated Heroku app.
http://mctheme-styleguide-sync.herokuapp.com/examples/bootstrap-css/bootstrap-css.html#buttons

**Comment by jamin-hall** [comment]
Hmm... I'm still seeing a few issues with active + hover states. The
buttons Matt pointed out look better, but here are a few examples where
it's still looking off. Maybe I need to clear my cache?

[image: Inline image 2]
[image: Inline image 3]

On Tue, Aug 25, 2015 at 2:48 PM, Stephen James <notifications@github.com>
wrote:

> Updated Heroku app.
>
> http://mctheme-styleguide-sync.herokuapp.com/examples/bootstrap-css/bootstrap-css.html#buttons
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExactTarget/fuelux-mctheme/pull/299#issuecomment-134699111>
> .
>



-- 

JAMIN HALL

Lead Interaction Designer | salesforce.com

Mobile: 317-701-4990

**Comment by mbeard** [comment]
The button dropdowns still seem to have the black font/border.  http://mctheme-styleguide-sync.herokuapp.com/examples/bootstrap-components/bootstrap-components.html#Button-dropdowns

**Comment by interactivellama** [comment]
Bootstrap appears to have added additional focus styles we need to also add. The standard site is using Bootstrap v3.2. the sync site is using BS Bootstrap v3.3.5. This is not a color reduction task. I can add to this PR, but it's a separate issue.

**Comment by interactivellama** [comment]
OK, I think I've the button thing figured out.

```
.btn-default {
	&:active,
	&:active:hover,
	&.active,
	&.active:hover,
	&:active:focus,
	&.active.focus,
	&:focus,
	&.focus,
	&.focus:active,
	&:hover {
		#gradient > .gradient-bg(@btn-default-bg-press-start, @btn-default-bg-press-end);
		color: @btn-default-color;
		border-color: @gray67;
	}
}
```

It's a mess!

**Comment by interactivellama** [comment]
Updated.

http://mctheme-styleguide-sync.herokuapp.com/examples/bootstrap-css/bootstrap-css.html#buttons
http://mctheme-styleguide-sync.herokuapp.com/examples/bootstrap-components/bootstrap-components.html#Button-dropdowns

**Comment by swilliamset** [comment]
Merging based on @mbeard's approval

**Pull request merged**
