### PR TITLE
Fixes tree to better match style guide.

### PR DESCRIPTION
**Pull request by chriscorwin**
Styles updated so that alignment is better, and matches style guide sizes too.

### CODE REVIEW

**Comment by chriscorwin** [comment]
screenshot 2015-02-09 17 57 40

**Comment by swilliamset** [comment]
Mixing margin and position absolute seems a bit odd

**Comment by chriscorwin** [comment]
Yes, well, the margin has to do with how far out the text sticks after the icon, and the absolute position places the checkmark and the dot centered within it's lil box.

**Comment by swilliamset** [comment]
I guess if it works...

**Comment by chriscorwin** [comment]
There was a mix of margin and abs position before I ever touched it --- I just massaged them into place better.

¯\_(ツ)_/¯

**Comment by interactivellama** [comment]
Something to look into.
screen shot 2015-02-09 at 6 07 29 pm

**Comment by interactivellama** [comment]
Do you think it needs more left padding on caret?

screen shot 2015-02-09 at 6 19 58 pm

**Comment by swilliamset** [comment]
This task PR does what it does but there are still issues with bouncing in the tree https://github.com/ExactTarget/fuelux-mctheme/issues/162

**Pull request merged**
